# Generated by Django 4.0.3 on 2022-05-04 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('fuel', models.CharField(max_length=30)),
                ('km', models.IntegerField()),
                ('engine_volume', models.IntegerField()),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_market.brand')),
            ],
        ),
    ]
