# Generated by Django 3.2.11 on 2022-05-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='km',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
